In [1]:
import torch

In [2]:
torch.rand(2,2)

tensor([[0.2788, 0.8997],
        [0.2280, 0.9480]])

In [5]:
x=torch.tensor([
    [0,0,1],
    [1,1,1],
    [0,0,0]
])
x

tensor([[0, 0, 1],
        [1, 1, 1],
        [0, 0, 0]])

In [6]:
x[0][0] = 5
x

tensor([[5, 0, 1],
        [1, 1, 1],
        [0, 0, 0]])

In [7]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [8]:
torch.ones(5,2) + torch.ones(5,2)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.]])

In [15]:
x = x.to(dtype=torch.float32)

In [16]:
x.max()

tensor(5.)

In [17]:
x.max().item()

5.0

Reshaping tensors

Using `reshape` is usually better, although it creates a copy (`view` can lead to various memory complications, like the tensor no longer being contiguous)

In [18]:
flat = torch.rand(784)

In [21]:
viewed = flat.view(1,28,28)
viewed.shape

torch.Size([1, 28, 28])

In [22]:
reshaped = flat.reshape(1, 28, 28)
reshaped.shape

torch.Size([1, 28, 28])

We can also permute tensors, for example getting a height, width, channel image into channel, height, width

In [23]:
hwc = torch.rand(640, 480, 3)
chw = hwc.permute([2,0,1])
chw.shape

torch.Size([3, 640, 480])